server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        data: DEBUG