server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://admin:passw0rd@localhost:27017/chat_app
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        data: DEBUG